### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by TanvirOnGH** [TanvirOnGH/opus-magnum-solutions#1]
## Prologue : The Transmutation Engine
1. [ ] Stabilized Water

## Chapter 1: Life in a Great House
1. [ ] Refined Gold
2. [ ] Face Powder
3. [ ] Waterproof Sealant
4. [ ] Hangover Cure
5. [ ] Airship Fuel
6. [ ] Precision Machine Oil
7. [ ] Health Tonic
8. [ ] Stamina Potion

## Chapter 2: Unprecedented Actions
1. [ ] Hair Product
2. [ ] Rocket Propellant
3. [ ] Mist of Incapacitation
4. [ ] Explosive Phial 
5. [ ] Armor Filament
6. [ ] Courage Potion
7. [ ] Surrender Flare

## Chapter 3: Exile and Thievery
1. [ ] Alcohol sepration
2. [ ] Water Purifier
3. [ ] Seal Solvent
4. [ ] Climbing Rope Fiber
5. [ ] Warming Tonic
6. [ ] Life Sensing Potion
7. [ ] Very Dark Thread

## Chapter 4: An Uncommon Ally
1. [ ] Litharge Separation
2. [ ] Stain Remover
3. [ ] Sword Alloy
4. [ ] Invisible Ink
5. [ ] Purified Gold
6. [ ] Alchemical Jewel
7. [ ] Golden Thread

## Chapter 5: Opposing Plots
1. [ ] Mist of Hallucination
2. [ ] Timing Crystal
3. [ ] Voltaic Coil
4. [ ] Unstable Compound
5. [ ] Curious Lipstick
6. [ ] Universal Solvent

### Reference
* [opus-magnum products wiki](https://bw.artemislena.eu/opus-magnum/wiki/Products)

**Comment by TanvirOnGH** [comment]
Well, the puzzles were very easy to solve.

**Comment by TanvirOnGH** [comment]
Well, the base puzzles were pretty easy to solve. The appendix puzzles are going to be a bit tricky since the space is limited and the journal of alchemical engineering puzzles are extremely complex and hard to solve, they'll require days if not weeks to solve each puzzle. I'll try to cover all of them in my free-time. I might design and solve puzzles, I'll make sure to share my designs for others to solve as well.
